// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yoiyefubulntththatig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvaXllZnVidWxudHRodGhhdGlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzY3ODMsImV4cCI6MjA2NTY1Mjc4M30.KAshnozai7QrDjtbNGbc7OE1JCVxATz9KJJjoVjNO_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);